### ISSUE TITLE
Repo cleanup and code

### ISSUE THREAD

**Issue by dacb** [ryan0124/ACEP_Capstone_Project#2]
I see your file https://github.com/ryan0124/ACEP_Capstone_Project/blob/main/LINCENSE.md is misspelled. I don't see the doc directory in the main branch or any code.

**Comment by abhineetnigam** [comment]
Hi Prof. Beck,
I corrected the typo in the License. As we are doing all our coding in Google Colab, we did not update it here. I have saved a copy of the colab on the repo now.
